FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY app.py emb.py k8s.txt embed.py text_to_embed.py __init__.py text_to_embed.py get_keyword.py ./
RUN pip install fastapi uvicorn chromadb ollama scrapling
RUN python emb.py
RUN python text_to_embed.py
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
